# Numpy 개요

Numeric + Python = Numpy
수학 및 과학 연산을 위한 파이썬 패키지
배열이나 행렬 계산에 용이한 메서드를 제공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
관련 사이트 : http://www.numpy.org

일반 List에 비해 빠르고, 메모리 효율적

반복문 없이 데이터 배열에 대한 처리를 지원함
선형대수와 관련된 다양한 기능을 제공함
Reference Site
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS
설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy

In [6]:
import numpy as np
np.__version__

'1.26.4'

## 넘파이 배열 이해하기

몇 차원인지 반환

In [2]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [3]:
a = np.array([2,4,5])
a, a.ndim, type(a)

(array([2, 4, 5]), 1, numpy.ndarray)

In [4]:
# 2차원
a = [[1,2,3],[4,5,6]]
a
# 리스트는 그냥 요소가 두개인 

[[1, 2, 3], [4, 5, 6]]

In [6]:
a = np.array([[1,2,3],[4,5,6]])
a, a.ndim,type(a)

#메트릭스로 나옴, 차원이 많으면 괄호 갯수 확인

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [7]:
# 3차원
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [8]:
a.shape

(2, 2, 3)

In [9]:
a.shape?
# 2행 3열이 2개가 있다는 뜻

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

## shape
행렬의 차원으로, 몇행 몇열인지 반환
아래의 경우 1차원에 4, 2차원에 2로 (4,2)로 표현됨

In [10]:
a = np.array(3)
a, a.shape # 행렬이 아니기떄문에 차원 반환 안됨

(array(3), ())

In [13]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape
# 5개 요소가 들어있다. 행렬로. 1차원 벡터

(array([1, 3, 5, 7, 9]), (5,))

In [14]:
a = np.array([[1,2,3],[4,5,6]])
a, a.shape
#2차원

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [15]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열
# 3차

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## 넘파이 배열
리스트를 넘파이 배열로 생성 np.array(리스트)   
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [17]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [18]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [19]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [21]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )
# size는 요소의 갯수, 길이는 행의 갯수
# 2차원은 1차원이 세개가 있다~ 

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [23]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [24]:
# 길이가 달라 에러 리턴
# 브로드캐스팅은 행렬 연산에만 가능. 
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
* 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)   
* 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등   
* 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [26]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [27]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [29]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype   
https://numpy.org/doc/stable/reference/arrays.dtypes.html   
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.   
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다   
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.

In [31]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)
# 리스트는 됨. 다양한 자료형 수용해

['안녕', 100, 3.14, True, False]


In [33]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)
# 수용할 수 있는 더 큰 자료형으로 통일시켜버림
# 안녕이 가장큼. 그 다음은 소숫점

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [34]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


##Inf와 NaN   
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.   
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.   
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [35]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
# 배열 연산은 무한대로 표현 

C:\Users\hsh97\AppData\Local\Temp\ipykernel_13252\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\hsh97\AppData\Local\Temp\ipykernel_13252\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [36]:
np.log(0)

C:\Users\hsh97\AppData\Local\Temp\ipykernel_13252\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [37]:
np.exp(-np.inf)

0.0

## 기술통계

In [38]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [41]:
x.mean()
# avg(평균) = mean

4.8076923076923075

In [42]:
np.mean(x)  # 평균

4.8076923076923075

In [43]:
np.var(x)  # 분산

115.23224852071006

In [44]:
np.std(x)  # 표준 편차

10.734628476137871

In [45]:
np.max(x)  # 최댓값

23

In [46]:
np.min(x)  # 최소값

-24

In [47]:
np.median(x)  # 중앙값

5.0

## 사분위수   
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.   
각각 1사분위수, 2사분위수, 3사분위수라고 한다.   
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.   
   
때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.   

In [48]:
np.percentile(x, 0)  # 최소값
# 데이터를 넣고 0에 대한 위치를 알려줘

-24.0

In [49]:
np.percentile(x, 25)  # 1사분위 수
#x고 25% 위치에 대한걸 알려줘

0.0

In [50]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [51]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [52]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기   
np.ones(n) , np.ones((x, y))   
np.zeros(n) , np.zeros((x, y))   
np.empty(n) , np.empty((x, y))   
np.aranges(start, end step)   
   
reshape(x, y) # 차원 확대   
flatten(x, y) # 차원 축소   

In [53]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 
# 연산을 1로 초기화하는 이유 : 특정 값을 유지하고 싶을 때 사용

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [54]:
print(np.ones((2,4)), np.ones((2,4)).dtype)
# 2행4열로 만들어줘

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [55]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [ ]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

In [56]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [57]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [58]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [59]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[      0       1       0]
 [5570652    1608       0]
 [    768   32763 3604537]]


In [60]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [62]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [63]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [64]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [65]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x00000166E4843C40>
File:            c:\users\hsh97\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end v

In [66]:
np.logspace?

Signature:      
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Call signature:  np.logspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function logspace at 0x00000166E4843E20>
File:            c:\users\hsh97\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.25.0
    Non-scalar 'base` is now supported

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in l

In [67]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열   
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,   
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.   

In [68]:
arr, arr.ndim, arr.shape
# 구조 변경하고 싶을때 사

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [69]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [70]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [71]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [72]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [73]:
print(np.arange(2,101,2).reshape(5,10))
# 메서드 체이닝을 통해 한번에 만들수도 있음

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [74]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [75]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape
# 1부터 31까지의 데이터를 리셰이프해줘. 근데 앞에 요소를 넣으면 그거에 맞게 사이즈 맞춰줘, 1열로 맞춰주고 행은 알아서 맞춰줘라
# 2차원 

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

## quiz5행4열을 만들어라

In [79]:
arr4 = np.arange(1, 21).reshape(5, 4)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 2,
 (5, 4))

In [80]:
# 01 사용해서 5열인 모형으로 바꿔
# 사이즈는 맞아야 함
arr4 = np.arange(1, 21).reshape(-1, 5)
arr4, arr4.ndim, arr4.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 2,
 (4, 5))

In [81]:
arr4 = np.arange(1, 21).reshape(-1, 7)
# 어레이는 이뮤터블하기 떄문에 사이즈 꼭 맞춰야

ValueError: cannot reshape array of size 20 into shape (7)

In [82]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [83]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [84]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [85]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [86]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환  
배열명2 = 배열명1.astype(자료형)   
자료형 = np.float64, np.int32

In [87]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [88]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [89]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [90]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype
# str은 먹지 않음. 문자열은 dtype 규칙대로 해야함

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [91]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [92]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [93]:
# 불린 -> 정수
matrix2.astype(int)
# stype으로 하면 int형으로 형 변환 

array([1, 0, 1, 1])

In [94]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [95]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [96]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가
# 숫자를 문자로 하는건 가능. 문자를 숫자로 표현하는건 제약이 있음.숫자의 특징에 맞춰야 가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [97]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱   
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [100]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [101]:
a[0]

1

In [102]:
a[2]

5

In [103]:
a[4]

9

In [104]:
a[-1]

9

In [105]:
a[-3]

5

In [106]:
a[-5]

1

In [107]:
a[[0, 2, 4]]

array([1, 5, 9])

In [108]:
a

array([1, 3, 5, 7, 9])

In [109]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] ) #2차원
b

array([[1, 3],
       [4, 2]])

In [110]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [111]:
#를 조회할건데 인덱싱이 가능할까?
# 넘파이 배열1을 넘파이 배열2로 인덱싱하는 경우, 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [112]:
print(a)
a[2] = 0
print(a)

[1 3 5 7 9]
[1 3 0 7 9]


In [113]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [114]:
a[0] += 6
a

array([7, 5, 0, 7, 9])

## 2D array

In [115]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [116]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
# 인데깅 값이 하나일 경우에는 행 인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [117]:
a[1]

array([5, 6, 7, 8, 9])

In [118]:
a[2]

array([10, 11, 12, 13, 14])

In [119]:
a[-1]

array([10, 11, 12, 13, 14])

In [120]:
a[-2]

array([5, 6, 7, 8, 9])

In [123]:
# 인덱싱값이 2ㅐ 들어가면 행/열 인덱싱
a[0,0]

0

In [124]:
a[2, 4]

14

In [125]:
a[1, 3]

8

In [126]:
a[-1, -1]

14

In [133]:
a[1,-1]

9

In [134]:
a[1][-1]

9

In [127]:
# 값 변경 가능
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [128]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [129]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [130]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

## 넘파이배열 슬라이싱   
1차원   
넘파이배열[:end]   
넘파이배열[start:]   
넘파이배열[start:end]   
넘파이배열[start:end:step]   
   
2차원   
넘파이배열[행, 열] = [start:end:step,    start2:end2:step2]   

### 1D array

In [136]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [137]:
a[:]

array([1, 3, 5, 7, 9])

In [138]:
 a[1:]

array([3, 5, 7, 9])

In [139]:
a[-1:]

array([9])

In [140]:
a[:3]

array([1, 3, 5])

In [141]:
a[:-1]

array([1, 3, 5, 7])

In [142]:
a[1:4]

array([3, 5, 7])

In [143]:
a[1:-1]

array([3, 5, 7])

In [144]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
a[::2]

array([0, 2, 4, 6, 8])

In [146]:
a[::5]

array([0, 5])

In [147]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [148]:
# 홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [149]:
a[3::2]

array([3, 5, 7, 9])

In [150]:
a[:-2:2]

array([0, 2, 4, 6])

In [151]:
a[:-6:2]

array([0, 2])

In [152]:
a[2:-2:2]

array([2, 4, 6])

In [153]:
# 거꾸로 나열
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2D array

In [2]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

NameError: name 'np' is not defined

In [155]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [156]:
a[1:] #2,3번째 행

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [157]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [158]:
a[:-3]

array([], shape=(0, 5), dtype=int32)

In [159]:
a[:, :] # 행의 범위, 열의 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [160]:
# 행은 전체가 필요해, 열은 1번 인덱스부터
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [161]:
a[: , 4:]

array([[14],
       [19],
       [24]])

In [165]:
a[1:,2:3]

array([[17],
       [22]])

In [167]:
a[:-1, 1:-1]

array([[11, 12, 13],
       [16, 17, 18]])

In [168]:
a[:2, 1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [169]:
a[1,2]

17

In [7]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

SyntaxError: invalid syntax (3690637699.py, line 1)

In [9]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

NameError: name 'matrix_c' is not defined

In [11]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\hsh97\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\hsh97\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initial

In [12]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([4, 2, 8, 4, 2, 9, 8, 7, 6, 7])

In [13]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5)) #넘파이는 행렬구조가 특징

array([[5, 9, 9, 2, 1],
       [1, 7, 6, 3, 1]])

## 섞기

np.random.shuffle(넘파이배열) 원본에 바로 적용

In [15]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.random.shuffle(matrix_e)
matrix_e

array([ 7,  3,  8,  9,  4,  1, 10,  6,  2,  5])

## Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [17]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]


array([ 7, 10, 36, 29, 38, 43])

In [18]:
np.random.randint(1,46,6)

array([ 9,  1,  2, 19, 17,  1])

## 실수 난수

In [19]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [ ]:
# 값을 두개 넣으면 행과 열의 구조를 의미 

In [20]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 0.92164277, -0.18617245,  0.1917604 , -1.35841461,  1.23235099,
       -1.86653871,  0.57848529,  1.7981364 , -1.33877183,  1.06682527])

In [21]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-1.39084747, -0.91626708,  0.41320439,  2.27613605],
       [-1.85584778,  0.55761389,  0.58531112,  1.5333832 ],
       [-0.98993552,  0.38599191, -0.02116855,  0.08198613],
       [-0.09851865, -0.28484033, -0.20184469,  0.74539548]])

In [22]:
matrix1.max(), matrix1.min()

(1.798136404789647, -1.8665387109310587)

## 집계함수에서의 축

2차원에서의 집계합수(sum, mean)   
axis = 0, 1   
np.sum(넘파이배열, axis=0/1)   
np.mean(넘파이배열, axis=0/1)   
np.sort(넘파이배열, axis=0/1)   

In [27]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[45, 15,  8, 34, 40],
       [48,  9, 11, 45, 37],
       [13,  5, 32,  4, 36],
       [37, 37, 14, 13, 14],
       [ 5, 24, 34, 48,  5]])

In [28]:
np.sum(m1, axis=0) # (x)열 합계(행방향 합계)

array([148,  90,  99, 144, 132])

In [29]:
np.sum(m1, axis=1) # 행 합계(열 방향 합계)

array([142, 150,  90, 115, 116])

In [26]:
# 1번째행의 합계는
m1[0,:]

array([16,  7, 15, 45,  1])

In [30]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

142

## quiz

In [32]:
# 3번째 열의 합계
np.sum(m1[:,2], axis=0) # 행은 전부 뽑아오고 열은 두번째 인덱스

99

## np.sort()

In [33]:
import numpy as np

In [34]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[10, 44, 19],
       [38, 31, 33],
       [43,  5, 21],
       [41, 10, 34]])

In [35]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x0000021AB9D6C5E0>
File:            c:\users\hsh97\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of

In [38]:
m2

array([[10, 44, 19],
       [38, 31, 33],
       [43,  5, 21],
       [41, 10, 34]])

In [36]:
np.sort(m2) # 행안에서 열정렬 #default axis = -1

array([[10, 19, 44],
       [31, 33, 38],
       [ 5, 21, 43],
       [10, 34, 41]])

In [40]:
np.sort(m2, axis = 1) 

array([[10, 19, 44],
       [31, 33, 38],
       [ 5, 21, 43],
       [10, 34, 41]])

In [37]:
np.sort(m2, axis = 0) # 행안에서 열정렬 #default axix = -1
# 행방향 오름차순(요소별로)

array([[10,  5, 19],
       [38, 10, 21],
       [41, 31, 33],
       [43, 44, 34]])

In [39]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[41, 10, 34],
       [43,  5, 21],
       [38, 31, 33],
       [10, 44, 19]])

In [41]:
m2

array([[10, 44, 19],
       [38, 31, 33],
       [43,  5, 21],
       [41, 10, 34]])

In [42]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[10, 19, 44],
       [31, 33, 38],
       [ 5, 21, 43],
       [10, 34, 41]])

In [43]:
m2[::-1, ::-1] 

array([[34, 10, 41],
       [21,  5, 43],
       [33, 31, 38],
       [19, 44, 10]])

## 인덱스 소팅

np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [44]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [45]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제

In [ ]:
삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [46]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [48]:
m3[0]

1

In [49]:
m3[-1]

10

In [50]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [51]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [52]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [54]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [55]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [56]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [57]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [59]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [60]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [62]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [63]:
## 배열 합치기
np.vstack((배열1,배열2....)) : 세로 합치기
np.hstack((배열1,배열2....)) : 가로 합치기
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

SyntaxError: invalid syntax. Perhaps you forgot a comma? (618624300.py, line 2)

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [66]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [67]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [68]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [69]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask

* 조건절의 결과는 True, False로 반환   
* 
True인 결과의 데이터 반
* 
넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [70]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [72]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
len(matrix[matrix > 10]) # 3단계

10

In [74]:
np.sum(matrix > 10) # 2단계

10

## Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [75]:
num = np.random.randint(1, 100, 30)
(num > 30) & (num < 70)

array([ True, False, False, False, False,  True,  True, False,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False, False, False])

In [76]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([72, 49, 63, 38, 49,  4, 87, 56, 12, 39,  7, 35, 40, 46, 27,  6, 12,
        16, 69, 84, 41, 54,  2,  5, 81, 29, 57, 29, 46, 63]),
 array([49, 63, 38, 49, 56, 39, 35, 40, 46, 69, 41, 54, 57, 46, 63]))

In [77]:
num = np.random.randint(1,100,30)
num[(num > 30) & (num < 70)]

array([31, 54, 49, 44, 66, 46, 44, 64, 35, 56, 33])

In [79]:
a = np.random.randint(1, 100, 30)
b = a[a>30]
b[b<70]

array([44, 45, 58, 41, 32, 64, 43, 47, 60, 48])

In [80]:
m2 = np.random.randint(1,100, (5,6))
m2, m2[(m2 > 30) & (m2 < 70)]

(array([[39, 46, 46, 44, 78, 51],
        [76, 94, 69, 72, 17, 62],
        [90,  3, 79, 80, 69, 29],
        [70, 94, 76, 99, 75, 50],
        [21, 10, 19, 50, 53, 90]]),
 array([39, 46, 46, 44, 51, 69, 62, 69, 50, 50, 53]))

In [81]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([ 5, 30,  9,  6, 28, 12])

### 10보다 작거나 90보다 큰 수 출력하기

In [82]:
num[(num < 10) | (num > 90)]

array([ 5,  9,  6, 97, 99])

In [83]:
num[~(num < 10) | (num > 90)]

array([31, 85, 81, 30, 54, 49, 84, 83, 97, 85, 44, 66, 86, 46, 89, 71, 44,
       64, 35, 56, 28, 82, 86, 33, 12, 82, 99])

## fancy indexing(filtering)

넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

* 넘파이배열1[넘파이배열2]   
* 넘파이배열2 : 인덱스 역할 (only 정수형)

In [84]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([37, 98, 41, 72, 87, 27, 82,  8, 62, 34, 47, 72, 56,  7, 42,  3, 56,
        54, 12, 75, 57, 86, 94, 26, 22, 45,  9, 96, 47, 33]),
 array([37, 41, 72, 47, 57]))

## np.where()를 이용한 필터링   
* np.where(조건식) : 조건식 만족하는 인덱스 반환   
* np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값   
* 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [85]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [86]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [87]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))